hmLoadTopic({
hmKeywords:"Aankoop bestelbon",
hmTitle:"Aankoopbestelbon",
hmDescription:"Met behulp van de aankoop bestelbonnen kunt u: Per document bijhouden bij wie en wat er besteld wordt De regels in het videodocument toevoegen met behulp van de keuze \'*...",
hmPrevLink:"backorders.html",
hmNextLink:"aankoop_leveringsbon.html",
hmParentLink:"voorraadbeheer2.html",
hmBreadCrumbs:"<a href=\"voorraadbeheer2.html\">Voorraad- &amp; aankoopbeheer<\/a>",
hmTitlePath:"Voorraad- & aankoopbeheer > Aankoop bestelbon",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Aankoopbestelbon<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">Met behulp van de aankoop bestelbonnen kunt u:<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Per document bijhouden bij wie en wat er besteld wordt<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>De regels in het videodocument toevoegen met behulp van de keuze \'<a href=\"aankoop_bestelbon.html\" class=\"topiclink\">* Overbrengen\'<\/a>:<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin: 0 0 0 4.5000rem;\"><span class=\"f_Normal\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">1.<\/span>Besteladviezen<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin: 0 0 0 4.5000rem;\"><span class=\"f_Normal\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">2.<\/span>Verkoopdocumenten (offertes, bestelbonnen, leveringsbonnen)<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin: 0 0 0 4.5000rem;\"><span class=\"f_Normal\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">3.<\/span>Openstaande backorders<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><a href=\"aankoop_bestelbon.html\" class=\"topiclink\">Besteldocument printen<\/a> om deze door te faxen of te e-mailen<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><a href=\"aankoop_bestelbon.html\" class=\"topiclink\">Bestelaantallen doorboeken<\/a> naar artikelbestand<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><a href=\"aankoop_bestelbon.html\" class=\"topiclink\">De videoregels van één aankoopbestelbon verplaatsen naar een ander aankoopbestelbon<\/a><\/p>"
})
