hmLoadTopic({
hmKeywords:"",
hmTitle:"Betaalagenda licentie",
hmDescription:"De banklinkmodule is een afzonderlijke module, die niet behoort tot het basispakket van de boekhouding. Zonder deze specifieke licentie zal de banklinkmodule niet werken.",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Technische info",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Betaalagenda licentie<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">De banklinkmodule is een afzonderlijke module, die niet behoort tot het basispakket van de boekhouding. Zonder deze specifieke licentie zal de banklinkmodule niet werken.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">Controleer ook zeker de volgende instellingen:<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_InstructieCommando\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">1.<\/span><span class=\"f_InstructieCommando\">Selecteer vanuit het hoofdmenu \'1 Aankoopdagboek\'.<\/span><br \/>\n\r<span class=\"f_InstructieResultaat\">U komt in het aankoopdagboek terecht. <\/span><br \/>\n\r<img alt=\"clip0241\" style=\"width:80%;max-width:1906px;height:auto;border:none\" src=\".\/images\/clip0241.jpg\"\/><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_InstructieCommando\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">2.<\/span><span class=\"f_InstructieCommando\">Selecteer \'Extra\'.<\/span><br \/>\n\r<span class=\"f_InstructieResultaat\">U krijgt dit keuzevenster te zien:<\/span><br \/>\n\r<img alt=\"clip0242\" style=\"width:100%;max-width:367px;height:auto;border:none\" src=\".\/images\/clip0242.jpg\"\/><\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 1.5000rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_InstructieCommando\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">3.<\/span><span class=\"f_InstructieCommando\">Selecteer \'Instellingen documenten\'.<\/span><br \/>\n\r<span class=\"f_InstructieResultaat\">Het instellingenscherm van de dagboeken verschijnt.<\/span><br \/>\n\r<img alt=\"clip0243\" style=\"width:80%;max-width:555px;height:auto;border:none\" src=\".\/images\/clip0243.jpg\"\/><\/p>\n\r<p class=\"p_InstructieCommando\"><span class=\"f_InstructieCommando\">&nbsp;<\/span><\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.8750rem; margin-left: 0.8750rem;\"><span class=\"f_InstructieCommando\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">4.<\/span><span class=\"f_InstructieCommando\">Aanpassen veld<\/span><br \/>\n\rZorg ervoor dat bij \'Betaalagendaregel aanmaken na toevoegen boekstuk\' een \'J\' staat ingevuld.<br \/>\n\r<img alt=\"clip0244\" style=\"width:100%;max-width:503px;height:auto;border:none\" src=\".\/images\/clip0244.jpg\"\/><\/p>"
})
