hmLoadTopic({
hmKeywords:"boekhoudjaar,Boekhoudjaar openen,Het boekhoudjaar openen,Ingave beginsaldi klanten\/leveranciers,Ingave beginsbalans,Opstellen boekhoudplan,Opstellen klantenbestand,Opstellen leveranciersbestand",
hmTitle:"De zes starthandelingen",
hmDescription:"Om u bij uw eerste stappen in het AXITO-boekhoudprogramma te begeleiden, hebben we de belangrijkste basisstappen gebundeld. Dit zijn de zes beschreven starthandelingen: ",
hmPrevLink:"dubbel-boekhouden.html",
hmNextLink:"het-eerste-boekjaar-openen.html",
hmParentLink:"boekhouding_algemeen.html",
hmBreadCrumbs:"<a href=\"boekhouding_algemeen.html\">Boekhouding<\/a>",
hmTitlePath:"Boekhouding > De zes starthandelingen",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">De zes starthandelingen<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">Om u bij uw eerste stappen in het AXITO-boekhoudprogramma te begeleiden, hebben we de belangrijkste basisstappen gebundeld. Dit zijn de zes beschreven starthandelingen: <\/p>\n\r<p style=\"line-height: 1.38; margin: 0 0 0.6875rem 0;\"><span style=\"font-size: 0.91rem; font-family: Arial,Helvetica,sans-serif; color: #000000;\">&nbsp;<\/span><\/p>\n\r<p style=\"text-indent: 0; line-height: 1.38; padding-left: 1.5000rem; margin: 0 0 0.6875rem 2.2500rem;\"><span class=\"f_Normal\" style=\"color:#000000;display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">1.<\/span><span style=\"color: #000000;\"><a href=\"het-eerste-boekjaar-openen.html\" class=\"topiclink\">Het eerste boekjaar openen<\/a><\/span><\/p>\n\r<p style=\"text-indent: 0; line-height: 1.38; padding-left: 1.5000rem; margin: 0 0 0.6875rem 2.2500rem;\"><span class=\"f_Normal\" style=\"color:#000000;display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">2.<\/span><span style=\"color: #000000;\"><a href=\"het-opstellen-van-het-boekhoudplan.html\" class=\"topiclink\">Opstellen van het boekhoudplan<\/a><\/span><\/p>\n\r<p style=\"text-indent: 0; line-height: 1.38; padding-left: 1.5000rem; margin: 0 0 0.6875rem 2.2500rem;\"><span class=\"f_Normal\" style=\"color:#000000;display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">3.<\/span><span style=\"color: #000000;\"><a href=\"het-opstellen-van-het-klantenbestand.html\" class=\"topiclink\">Opstellen van het klantenbestand<\/a><\/span><\/p>\n\r<p style=\"text-indent: 0; line-height: 1.38; padding-left: 1.5000rem; margin: 0 0 0.6875rem 2.2500rem;\"><span class=\"f_Normal\" style=\"color:#000000;display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">4.<\/span><span style=\"color: #000000;\"><a href=\"het-opstellen-van-het-leveranciersbestand.html\" class=\"topiclink\">Opstellen van het leveranciersbestand<\/a><\/span><\/p>\n\r<p style=\"text-indent: 0; line-height: 1.38; padding-left: 1.5000rem; margin: 0 0 0.6875rem 2.2500rem;\"><span class=\"f_Normal\" style=\"color:#000000;display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">5.<\/span><span style=\"color: #000000;\"><a href=\"ingeven-van-de-beginsaldi.html\" class=\"topiclink\">Ingeven van de beginsaldi van klanten\/leveranciers<\/a><\/span><\/p>\n\r<p style=\"text-indent: 0; line-height: 1.38; padding-left: 1.5000rem; margin: 0 0 0.6875rem 2.2500rem;\"><span class=\"f_Normal\" style=\"color:#000000;display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">6.<\/span><span style=\"color: #000000;\"><a href=\"ingeven-van-de-beginbalans.html\" class=\"topiclink\">Ingeven van de beginbalans<\/a><\/span><\/p>"
})
