hmLoadTopic({
hmKeywords:"",
hmTitle:"Detailrekeningen",
hmDescription:"In het hoofdmenu kunt u via <U> Boekhoudplan het onderstaande menu oproepen. In dit menu vindt u niet enkel het MAR en het boekhoudplan terug, maar sinds versie 2020.00 vindt u...",
hmPrevLink:"btw-vakken.html",
hmNextLink:"detailrekeningen-configureren.html",
hmParentLink:"boekhouding_algemeen.html",
hmBreadCrumbs:"<a href=\"boekhouding_algemeen.html\">Boekhouding<\/a>",
hmTitlePath:"Boekhouding > Detailrekeningen",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Detailrekeningen<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">In het hoofdmenu kunt u via &lt;U&gt; Boekhoudplan het onderstaande menu oproepen. In dit menu vindt u niet enkel het MAR en het boekhoudplan terug, maar sinds versie 2020.00 vindt u ook de keuze &lt;D&gt;etailrekeningen in dit menu.<\/p>\n\r<div class=\"p_Normal\"><img alt=\"clip0323\" style=\"width:100%;max-width:242px;height:auto;border:none\" src=\".\/images\/clip0323.jpg\"\/><\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h2 class=\"p_Heading2\"><span class=\"f_Heading2\">Wat is een detailrekening? <\/span><\/h2>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Een detailrekening is een nevenrekening waarop u een boeking kunt specificeren. Bijvoorbeeld: u boekt de onderhoudsfactuur voor de wagen van uw werknemer op de grootboekrekening 612010, maar in plaats van aparte grootboekrekeningen te maken voor elke wagen in uw wagenpark, voert u bij deze boeking de detailrekening van de wagen in kwestie in. Op die manier staan alle facturen van alle onderhoudsbeurten (van elke wagen in uw wagenpark) straks op 612010, terwijl u nog steeds een overzicht kunt opvragen van de boeking verbonden met deze detailrekening.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Een detailrekening staat als het ware parallel ten opzichte van de grootboekrekeningen uit het boekhoudplan. Detailrekeningen en grootboekrekeningen staan in een n-op-n-relatie ten opzichte van elkaar. Dat betekent dat meerdere detailrekeningen gekoppeld kunnen worden aan een grootboekrekening, maar tegelijkertijd kan een detailrekening gekoppeld zijn aan verschillende grootboekrekeningen.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Er zijn verschillende soorten detailrekeningen. Op dit moment zijn de mogelijkheden beperkt tot een algemene detailrekening en een voertuig(detail)rekening, maar in de toekomst zal het aantal detailrekeningtypes uitgebreid worden. <\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
