hmLoadTopic({
hmKeywords:"",
hmTitle:"Doorboeken kassaverkopen naar Historiek kassaverkopen",
hmDescription:"Doorboeken ‘Kassaverkopen’ naar ‘Historiek kassaverkopen’",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Technische info",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Doorboeken kassaverkopen naar Historiek kassaverkopen<\/span><\/p>\n\r",
hmBody:"<h1 class=\"p_Heading1\"><a id=\"doorboeken_kassaverkopen\" class=\"hmanchor\"><\/a><span class=\"f_Heading1\">Doorboeken ‘Kassaverkopen’ naar ‘Historiek kassaverkopen’<\/span><\/h1>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Op het einde van de dag (of week) kunt u alle dagverkopen doorboeken naar het bestand \'Historiek verkopen\'. Voordat u de dagelijkse verkopen doorboekt, is het uiteraard noodzakelijk dat u eerst de dagontvangsten heeft geprint (eenmaal door geboekt, gaan een aantal gegevens verloren zoals beginwaarde kassa).<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Tijdens deze doorboeking worden een aantal handelingen uitgevoerd:<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>De verkopen worden gekopieerd naar het bestand \'Historiek verkopen\'. Zodoende kunt u nadien deze verkopen steeds raadplegen.<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>De voorraadgegevens worden aangepast. Tijdens de registratie van de verkopen wordt de voorraad niet aangepast<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>De door geboekte verkoopregels worden geschrapt. In het scherm van de verkopen wordt de beginkassawaarde aangepast, zodat u met een blanco ingavescherm kunt beginnen.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Tevens wordt de eindwaarde van de kassa getoond, zodat u altijd kunt controleren of dit overeenkomt met de werkelijke kassa-inhoud. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Voordat de gegevens worden door geboekt, worden deze nog gecontroleerd. De foutmelding die u dan kunt krijgen is “Kassaverkopen bevat regel(s) zonder kassaticketnummer !”. Dit betekend dat er verkopen bij zijn, die nog &nbsp;niet werden afgesloten. Dit is meestal de laatste verkoop, die werd ingegeven. U dient dan eerst in de verkopen deze op een correcte manier af te sluiten met de keuze ‘\/ Einde-Printen’<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
