hmLoadTopic({
hmKeywords:"",
hmTitle:"F1: Help",
hmDescription:"Doel U uit de nood helpen, als u \'vastzit\'.  Activeren Dit kunt u door: In de \'functietoetsen\' knoppenbalk op de knop F1 te klikken met de muis Door op <F1> te drukken op uw",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Technische info",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">F1: Help<\/span><\/p>\n\r",
hmBody:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Doel<\/span><\/h1>\n\r<p class=\"p_Normal\">U uit de nood helpen, als u \'vastzit\'.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Activeren<\/span><\/h1>\n\r<p class=\"p_Normal\">Dit kunt u door:<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.6875rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>In de \'functietoetsen\' knoppenbalk op de knop <a href=\"opbouw-axito-scherm.html\" class=\"topiclink\">F1<\/a> te klikken met de muis<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.6875rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Door op &lt;F1&gt; te drukken op uw <a href=\"het-toetsenbord.html#functietoetsen\" class=\"topiclink\">toetsenbord<\/a><\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 1.6875rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Vervolgens krijgt u in een browser de online AXITO-helptekst te zien. Het voordeel van deze \'online\' handleiding, ten opzichte van een geschreven handleiding, is dat u:<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin-left: 0.8750rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>De meest recentste handleiding ziet die beschikbaar is<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin-left: 0.8750rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>Onmiddellijk die informatie te zien krijgt, die betrekking heeft op hetgeen u op dat moment aan het doen bent. De getoonde informatie handelt over zaken waarover u zich op dat moment vragen kunt stellen.<\/p>"
})
