hmLoadTopic({
hmKeywords:"",
hmTitle:"F4: ASCII-tabel",
hmDescription:"Doel Het tonen van de ASCII-tabel.  Activeren Dit kunt u door: In de \'functietoetsen\' knoppenbalk op de knop F4 te klikken met de muis Door op <F4> te drukken op uw toetsenbo",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Technische info",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">F4: ASCII-tabel<\/span><\/p>\n\r",
hmBody:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Doel<\/span><\/h1>\n\r<p class=\"p_Normal\">Het tonen van de ASCII-tabel.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Activeren<\/span><\/h1>\n\r<p class=\"p_Normal\">Dit kunt u door:<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.6875rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>In de \'functietoetsen\' knoppenbalk op de knop <a href=\"opbouw-axito-scherm.html\" class=\"topiclink\">F4<\/a> te klikken met de muis<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.6875rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Door op &lt;F4&gt; te drukken op uw <a href=\"het-toetsenbord.html#functietoetsen\" class=\"topiclink\">toetsenbord<\/a><\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 1.6875rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">In totaal kunnen op het scherm 255 verschillende karakters worden weergegeven. Bijgevolg zou een toetsenbord ook moeten uitgevoerd zijn met 255 toetsen. Omdat dit onoverzichtelijk zou zijn, heeft men enkel de meest gebruikte toetsen op het toetsenbord ondergebracht. Een standaard toetsenbord beschikt over 102 toetsen. Binnen de ASCII-tabel hebben alle 255 karakters, elk een eigen getal gekregen. De ASCII-tabel vindt u tevens terug, in bijlage van deze handleiding.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<div class=\"p_Normal\" style=\"margin: 0 0 0 1.6250rem;\"><img alt=\"clip0364\" style=\"width:80%;max-width:1076px;height:auto;border:none\" src=\".\/images\/clip0364.png\"\/><\/div>\n\r<p class=\"p_Normal\" style=\"text-align: center; margin: 0 0 0 0;\">&nbsp;<\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.80; padding: 0 0 0 0; margin: 0 0 0 1.6250rem;\"><table class=\"Voorbeeld\" >\n\r<tr class=\"Voorbeeld\">\n\r<td class=\"Voorbeeld\"><p class=\"p_Normal\"><span style=\"font-weight: bold;\">Voorbeeld:<\/span><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">u wenst het speciale karakter φ in te geven. Dit gaat als volgt: Zoek het karakter φ op in de ASCII-tabel. U ziet dan dat het karakter φ overeenkomt met het getal 237. Dit getal dient u te onthouden. Vervolgens gaat u naar de plaats waar u het karakter φ wenst in te geven. Daarna drukt u op &lt;Alt&gt;. Terwijl u &lt;Alt&gt; ingedrukt houdt, geeft u via het numerisch klavier het getal 237 in. Vervolgens laat u &lt;Alt&gt; terug los. Op het scherm verschijnt het karakter \'φ\'.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
