hmLoadTopic({
hmKeywords:"Filter",
hmTitle:"Filter",
hmDescription:"Een filter biedt de mogelijkheid om records die aan één of meerdere (zelf te bepalen) voorwaarden voldoen, te filteren uit het huidige bestand. Records die niet aan die...",
hmPrevLink:"micromacro.html",
hmNextLink:"snelfilter.html",
hmParentLink:"de_verschillende_keuzes.html",
hmBreadCrumbs:"Algemeen &gt; <a href=\"de_verschillende_keuzes.html\">De \'Bewerkingen\' knoppenbalk<\/a>",
hmTitlePath:"Algemeen > De \'Bewerkingen\' knoppenbalk > Filter",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Filter<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">Een filter biedt de mogelijkheid om records die aan één of meerdere (zelf te bepalen) voorwaarden voldoen, te filteren uit het huidige bestand. Records die niet aan die voorwaarde(n) voldoen, worden niet dan niet getoond.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><span class=\"f_Heading1\">Werkwijze<\/span><\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin-left: 0.8750rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>Door op de knop \'Filter\' te klikken met de muis<\/p>\n\r<div class=\"p_Normal\" style=\"margin: 0 0 0 2.5000rem;\"><img alt=\"clip0530\" style=\"width:80%;max-width:616px;height:auto;border:none\" src=\".\/images\/clip0530.png\"\/><\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin-left: 0.8750rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>Door op de <a href=\"axito-smartkey.html\" class=\"topiclink\">smartkey<\/a> \'F\' van het toetsenbord te drukken (zoals aangegeven bij deze keuze in de rode kleur)<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Afhankelijk van waar u de keuze \'Filter\' gebruikt, kunt u<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin-left: 0.8750rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>Een snelfilter instellen <br \/>\n\r(Klanten, leveranciers, prospecten, artikelen, offertes, bonnen, facturen, grootboekrekeningen, boekhoudplan, intrastat, herstellingen, aankopen, projecten, ...)<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin-left: 0.8750rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>Een geavanceerde filter instellen<\/p>"
})
