hmLoadTopic({
hmKeywords:"Historieken",
hmTitle:"Historieken",
hmDescription:"Via de keuze \'Historieken\' kunt u bijkomende informatie opvragen, en dit vanuit verschillende invalshoeken.",
hmPrevLink:"diversen_artikelen.html",
hmNextLink:"intrastatcodes.html",
hmParentLink:"artikelen.html",
hmBreadCrumbs:"<a href=\"artikelenbeheer2.html\">Artikelenbeheer<\/a> &gt; <a href=\"artikelen.html\">Artikelen<\/a>",
hmTitlePath:"Artikelenbeheer > Artikelen > Historieken",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Historieken<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">Via de keuze \'Historieken\' kunt u bijkomende informatie opvragen, en dit vanuit verschillende invalshoeken.<\/p>\n\r<p class=\"p_Normal\">Deze mogelijkheden worden besproken in de keuze <a href=\"historieken_artikelen.html\" class=\"topiclink\">Historiek artikelen.<\/a><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><a id=\"historiek_historiek-samenvatting\" class=\"hmanchor\"><\/a><span class=\"f_Heading1\">Historiek-samenvatting<\/span><\/h1>\n\r<p class=\"p_Normal\">Via de keuze &lt;J&gt; krijgt u scherm te zien, de historiek-samenvatting. In dit scherm wordt een overzicht getoond van verschillende informatie, zoals:<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Huidige verkoopprijs<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Huidige aankoopprijs<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Huidige gemiddelde aankoopprijs<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Historiek verkopen: dit is een overzicht van de meest recente verkoopdocumenten (leveringsbonnen en facturen).<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Historiek aankoop-leveringsbonnen: Dit geeft een overzicht van de meest recente aankoop-leveringsbonnen voor dit artikel.<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Prijs-informatie: Dit geeft een overzicht van de meest recente prijzen van verschillende leveranciers (voor dit artikel).<\/p>"
})
