hmLoadTopic({
hmKeywords:"",
hmTitle:"Hoofdmenu",
hmDescription:"U kunt zelf bepalen hoe het hoofdmenu wordt weergegeven. Afhankelijk van het soort gebruiker kunt u dit instellen.",
hmPrevLink:"interface.html",
hmNextLink:"kolommen-in-de-browser.html",
hmParentLink:"interface.html",
hmBreadCrumbs:"<a href=\"overige_handleidingen.html\">Overige handleidingen<\/a> &gt; <a href=\"interface.html\">Interface instellingen<\/a>",
hmTitlePath:"Overige handleidingen > Interface instellingen > Hoofdmenu",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Hoofdmenu<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">U kunt zelf bepalen hoe het hoofdmenu wordt weergegeven. Afhankelijk van het soort gebruiker kunt u dit instellen.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Bovenaan in het AXITO-scherm kunt u de keuze Hoofdmenu selecteren (in de rode cirkel). In het menu dat dan verschijnt kunt u het gewenste menu selecteren.<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.8125rem;\"><img alt=\"clip0047\" style=\"margin:0;width:48.3750rem;height:26.3125rem;border:none\" src=\".\/images\/clip0047.png\"\/><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Momenteel zijn volgende menu beschikbaar. In volgende versies zal dit verder worden uitgebreid.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<div class=\"p_Normal\" style=\"margin: 0 0 0 0.8125rem;\"><div style=\"margin:0;width:28.6250rem\"><img alt=\"AXITO-Hoofdmenu\" title=\"AXITO-Hoofdmenu\" style=\"width:28.6250rem;height:13.7500rem;border:none\" src=\".\/images\/clip0048.png\"\/><p style=\"text-align:center\"><span class=\"f_ImageCaption\">AXITO-Hoofdmenu<\/span><\/p><\/div><\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<div class=\"p_Normal\" style=\"margin: 0 0 0 0.8125rem;\"><div style=\"margin:0;width:20.6250rem\"><img alt=\"Facturatie-hoofdmenu\" title=\"Facturatie-hoofdmenu\" style=\"width:20.6250rem;height:13.4375rem;border:none\" src=\".\/images\/clip0049.png\"\/><p style=\"text-align:center\"><span class=\"f_ImageCaption\">Facturatie-hoofdmenu<\/span><\/p><\/div><\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<div class=\"p_Normal\" style=\"margin: 0 0 0 0.8125rem;\"><div style=\"margin:0;width:29.6875rem\"><img alt=\"Boekhouding-Hoofdmenu\" title=\"Boekhouding-Hoofdmenu\" style=\"width:29.6875rem;height:11.9375rem;border:none\" src=\".\/images\/clip0050.png\"\/><p style=\"text-align:center\"><span class=\"f_ImageCaption\">Boekhouding-Hoofdmenu<\/span><\/p><\/div><\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<div class=\"p_Normal\" style=\"margin: 0 0 0 0.8125rem;\"><div style=\"margin:0;width:13.8125rem\"><img alt=\"Kassa-Hoofdmenu\" title=\"Kassa-Hoofdmenu\" style=\"width:13.8125rem;height:13.1250rem;border:none\" src=\".\/images\/clip0051.png\"\/><p style=\"text-align:center\"><span class=\"f_ImageCaption\">Kassa-Hoofdmenu<\/span><\/p><\/div><\/div>\n\r"
})
