hmLoadTopic({
hmKeywords:"",
hmTitle:"Inleiding",
hmDescription:"Beste lezer, Beste AXITO-gebruiker,  Welkom op onze online handleiding. Deze online handleiding is een naslagwerk dat u begeleidt bij het gebruiken van AXITO-Software. Onze hand",
hmPrevLink:"",
hmNextLink:"axito-in-de-cloud.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Inleiding",
hmHeader:"<div style=\"text-align: left; text-indent: 0; line-height: 1.80; padding: 0 0 0 0; margin: 0 0 0 0.8750rem;\"><table style=\"width:100%; border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:bottom; width:27.1875rem; padding:0; border:none\"><h1 class=\"p_Heading1\"><span class=\"f_Heading1\" style=\"font-size: 3.27rem; color: #ffffff;\">Inleiding<\/span><\/h1>\n\r<\/td>\n\r<td style=\"vertical-align:bottom; width:14.3125rem; padding:0; border:none\"><h1 class=\"p_Heading1\" style=\"text-align: center;\"><span style=\"font-size: 0.91rem; font-family: Arial,Helvetica,sans-serif; color: #000000;\"> &nbsp;<\/span><\/h1>\n\r<\/td>\n\r<td style=\"vertical-align:bottom; width:10.6250rem; padding:0; border:none\"><h1 class=\"p_Heading1\" style=\"text-align: center;\"><span class=\"f_Heading1\">&nbsp;<\/span><\/h1>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r",
hmBody:"<p class=\"p_Normal\">Beste lezer,<\/p>\n\r<p class=\"p_Normal\">Beste AXITO-gebruiker,<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Welkom op onze online handleiding. Deze online handleiding is een naslagwerk dat u begeleidt bij het gebruiken van AXITO-Software. Onze handleiding kunt u raadplegen op verschillende manieren: <\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Via onze website <a href=\"http:\/\/www.axito.com\/help\" target=\"_blank\" onclick=\"return HMTrackTopiclink(this);\" class=\"weblink\">www.axito.com\/help<\/a><\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Als een PDF-bestand (het PDF-bestand wordt geïnstalleerd op uw computer tijdens de installatie van de AXITO-Software). &nbsp;Aangezien onze software continu in ontwikkeling is, volgt deze online handleiding deze ontwikkeling op de voet. Wij doen ons uiterste best om deze handleiding op regelmatige basis bij te werken en de vernieuwde versie online te plaatsen. U kunt de laatste versie altijd downloaden.<\/p>\n\r<p class=\"p_Normal\" style=\"text-align: center;\"><input type=\"button\" class=\"weblink\" value=\"Download PDF-handleiding\" onclick=\"window.open(\'https:\/\/www.axito.com\/help\/AXITO%20Handleiding.pdf\')\" \/><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">We wensen u veel succes met onze software.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Het AXITO-team. <\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Indien u opmerkingen, vragen of bijkomende uitleg over deze handleiding nodig heeft, kunt u ons contacteren via <a href=\"mailto:support@axito.com\" target=\"_blank\" onclick=\"return HMTrackTopiclink(this);\" class=\"weblink\">support@axito.com<\/a><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
