hmLoadTopic({
hmKeywords:"",
hmTitle:"Kopieren factuur",
hmDescription:"Op deze manier kunt u een nieuwe factuur die gelijkaardig (zelfde artikelen en aantallen) is aan de originele op een gemakkelijke manier toevoegen. Via een dialoogvenster wordt...",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Technische info",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Kopieren factuur<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">Op deze manier kunt u een nieuwe factuur die gelijkaardig (zelfde artikelen en aantallen) is aan de originele op een gemakkelijke manier toevoegen. Via een dialoogvenster wordt gevraagd een aantal gegevens:<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Het factuurnummer van de originele factuur<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Het factuurnummer van de nieuwe factuur<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Het klantnummer van de nieuwe factuur<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Het projectnummer van deze factuur<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>De factuurdatum<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>De werknemersnummer<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Nadat u een bevestiging heeft gegeven, wordt de originele factuur gekopieerd naar een nieuwe factuur. De voorraad wordt hierbij automatisch aangepast. Uiteraard kunt u aan deze nieuwe factuur nog wijzigen aanbrengen, zoals de aantallen wijzigen, videoregels schrappen of nieuwe artikelen aan de factuur toevoegen.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Opmerking: de verschillende videoregel van deze nieuwe factuur krijgen allemaal een nieuw uniek trackingnummer, zodat deze volledig los staan van de originele videoregels.<\/p>\n\r"
})
