hmLoadTopic({
hmKeywords:"",
hmTitle:"Leverancierslisting",
hmDescription:"Vanuit het hoofdmenu (handelszaak) kiest u <6> Intervat \/ Btw.",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Technische info",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Leverancierslisting<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_InstructieCommando\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">1.<\/span><span class=\"f_InstructieCommando\">Vanuit het hoofdmenu (handelszaak) kiest u &lt;6&gt; Intervat \/ Btw.<\/span><br \/>\n\r<span class=\"f_InstructieResultaat\">U krijgt het volgende keuzemenu te zien:<\/span><br \/>\n\r<img alt=\"clip0282\" style=\"width:100%;max-width:461px;height:auto;border:none\" src=\".\/images\/clip0282.jpg\"\/><\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 1.5000rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 1.5000rem;\">&nbsp;<\/p>\n\r<p class=\"p_InstructieCommando\" style=\"text-indent: 0; padding-left: 1.8750rem; margin-left: 0.8750rem;\"><span class=\"f_InstructieCommando\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">2.<\/span><span class=\"f_InstructieCommando\">Druk op &lt;D&gt; Controlelijst Leverancierslisting.<\/span><br \/>\n\r<span class=\"f_InstructieResultaat\">Vervolgens ziet u een venster waarin u enkele basisgegevens moet invoeren of bevestigen. In het geval van de leverancierslisting zijn dit enkel het kalenderjaar en de munteenheid.<\/span><br \/>\n\r<img alt=\"clip0283\" style=\"width:100%;max-width:584px;height:auto;border:none\" src=\".\/images\/clip0283.jpg\"\/><\/p>\n\r<p class=\"p_InstructieCommando\"><span class=\"f_InstructieCommando\">&nbsp;<\/span><\/p>\n\r<p class=\"p_InstructieCommando\"><span class=\"f_InstructieCommando\">&nbsp;<\/span><\/p>\n\r<p class=\"p_InstructieCommando\" style=\"text-indent: 0; padding-left: 1.8750rem; margin-left: 0.8750rem;\"><span class=\"f_InstructieCommando\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">3.<\/span><span class=\"f_InstructieCommando\">Druk een laatste maal op &lt;Enter&gt;.<\/span><br \/>\n\r<span class=\"f_InstructieResultaat\">U ziet nu de leverancierslisting op het scherm verschijnen.<\/span><br \/>\n\r<img alt=\"clip0284\" style=\"width:100%;max-width:1457px;height:auto;border:none\" src=\".\/images\/clip0284.jpg\"\/><\/p>\n\r<p class=\"p_InstructieCommando\"><span class=\"f_InstructieCommando\">&nbsp;<\/span><\/p>\n\r<p class=\"p_InstructieCommando\"><span class=\"f_InstructieCommando\">&nbsp;<\/span><\/p>\n\r<p class=\"p_InstructieCommando\"><span class=\"f_InstructieCommando\">&nbsp;<\/span><\/p>\n\r<p class=\"p_InstructieCommando\"><span class=\"f_InstructieCommando\">&nbsp;<\/span><\/p>\n\r<p class=\"p_InstructieCommando\"><span class=\"f_InstructieCommando\">&nbsp;<\/span><\/p>\n\r<p class=\"p_InstructieCommando\"><span class=\"f_InstructieCommando\">&nbsp;<\/span><\/p>\n\r"
})
