hmLoadTopic({
hmKeywords:"",
hmTitle:"Nieuw boekhoudjaar starten (zonder het vorige af te sluiten)",
hmDescription:"Vraag: Kan ik een nieuw boekhoudjaar starten en dit zonder het huidige boekhoudjaar af te sluiten?  Antwoord: Het is mogelijk om een nieuw boekjaar te starten zonder het vorige",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Technische info",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Nieuw boekhoudjaar starten (zonder het vorige af te sluiten)<\/span><\/p>\n\r",
hmBody:"<h2 class=\"p_Heading2\"><span class=\"f_Heading2\">Vraag:<\/span><\/h2>\n\r<p class=\"p_Normal\">Kan ik een nieuw boekhoudjaar starten en dit zonder het huidige boekhoudjaar af te sluiten?<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h2 class=\"p_Heading2\"><span class=\"f_Heading2\">Antwoord:<\/span><\/h2>\n\r<p class=\"p_Normal\">Het is mogelijk om een nieuw boekjaar te starten zonder het vorige boekjaar te sluiten. Volg hiervoor deze procedure:<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">1.<\/span>Vanuit het hoofdmenu van de handelszaak selecteert u de keuze ‘<span style=\"font-weight: bold;\">+ Afsluiten periode<\/span>’<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">2.<\/span>Indien gevraagd wordt naar de boekingsdatum, gewoon bevestigen<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">3.<\/span>Vervolgens de keuze ‘<span style=\"font-weight: bold;\">Historiek boekhoudjaren<\/span>’ selecteren<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">4.<\/span>Nu worden de verschillende boekhoudjaren (die reeds aanwezig zijn) getoond<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">5.<\/span>Hier kunt u een nieuw boekjaar toevoegen via de keuze &lt;T&gt;oevoegen<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">6.<\/span>De gegevens voor het nieuwe boekjaar worden automatisch ingevuld, en dienen enkel maar bevestigd te worden (via de &lt;Enter&gt; toets)<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.2500rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"display:inline-block;width:1.2500rem;margin-left:-1.2500rem\">7.<\/span>Nadat het nieuwe boekjaar is toegevoegd, kunt u in het aan- of verkoopdagboek naar de volgende periode gaan via de &lt;+&gt; toets<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
