hmLoadTopic({
hmKeywords:"Nota",
hmTitle:"Nota",
hmDescription:"Bij de meeste bestanden kunt u aan ieder record een vrije tekst (nota) koppelen.",
hmPrevLink:"intrastat-keuze.html",
hmNextLink:"voldaan.html",
hmParentLink:"de_verschillende_keuzes.html",
hmBreadCrumbs:"Algemeen &gt; <a href=\"de_verschillende_keuzes.html\">De \'Bewerkingen\' knoppenbalk<\/a>",
hmTitlePath:"Algemeen > De \'Bewerkingen\' knoppenbalk > Nota",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Nota<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">Bij de meeste bestanden kunt u aan ieder record een vrije tekst (nota) koppelen.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><span class=\"f_Heading1\">Werkwijze<\/span><\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin-left: 0.8750rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>Door op de knop \'Nota\' te klikken met de muis<\/p>\n\r<div class=\"p_Normal\" style=\"margin: 0 0 0 2.5000rem;\"><img alt=\"clip0576\" style=\"width:80%;max-width:716px;height:auto;border:none\" src=\".\/images\/clip0576.png\"\/><\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin-left: 0.8750rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>Door op de <a href=\"axito-smartkey.html\" class=\"topiclink\">smartkey<\/a> \'N\' van het toetsenbord te drukken (zoals aangegeven bij deze keuze in de rode kleur)<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Weergave<\/span><\/h1>\n\r<p class=\"p_Normal\">Wanneer u \'Nota\' selecteert, wordt een nota-veld getoond<\/p>\n\r<div class=\"p_Normal\" style=\"margin: 0 0 0 2.5000rem;\"><img alt=\"clip0577\" style=\"width:80%;max-width:899px;height:auto;border:none\" src=\".\/images\/clip0577.png\"\/><\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Via de \'F5\' toets krijgt u een lijst waarin standaard nota\'s kunnen beheert worden. En via de keuze \'Overbrengen\' of \'Enter\' kunt u die standaard nota gemakkelijk invullen in dit nota-veld.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Nota\'s in macro\'s<\/span><\/h1>\n\r<p class=\"p_Normal\">Daarnaast wordt het nota-veld ook getoond in sommige macro-schermen. Enkele voorbeelden:<\/p>\n\r<div class=\"p_Normal\" style=\"margin: 0 0 0 2.5000rem;\"><img alt=\"clip0578\" style=\"width:80%;max-width:1202px;height:auto;border:none\" src=\".\/images\/clip0578.png\"\/><\/div>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 2.5000rem;\">&nbsp;<\/p>\n\r<div class=\"p_Normal\" style=\"margin: 0 0 0 2.5000rem;\"><img alt=\"clip0579\" style=\"width:80%;max-width:1216px;height:auto;border:none\" src=\".\/images\/clip0579.png\"\/><\/div>\n\r"
})
