hmLoadTopic({
hmKeywords:"",
hmTitle:"Openstaande facturen",
hmDescription:"Opgelet: Deze keuze enkel gebruiken indien u NIET met het AXITO-boekhoudprogramma werkt.",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Technische info",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Openstaande facturen<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">&nbsp;<\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.80; padding: 0 0 0 0; margin: 0 0 0 0.8125rem;\"><table class=\"Waarschuwing\" >\n\r<tr class=\"Waarschuwing\">\n\r<td class=\"Waarschuwing\"><p class=\"p_Normal\"><span style=\"font-size: 1.45rem; font-weight: bold; color: #ff0000;\">Opgelet: Deze keuze enkel gebruiken indien u NIET met het AXITO-boekhoudprogramma werkt.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.8125rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.8125rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Wanneer u de betaling van uw facturen wilt opvolgen, dan kunt u dit via deze keuze. Eerst krijgt u een menu met volgende keuzes :<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Alle facturen<\/span><\/h1>\n\r<p class=\"p_Normal\">Geeft een overzicht van alle facturen en de bijbehorende betalingen<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Reeds vervallen, openstaande verkoopfacturen<\/span><\/h1>\n\r<p class=\"p_Normal\">Toont alle facturen die nog niet zijn betaald en die reeds voorbij de vervaldatum zijn. Deze hadden dus eigenlijk al betaald moeten zijn.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Nog te vervallen, openstaande verkoopfacturen<\/span><\/h1>\n\r<p class=\"p_Normal\">Toont alle facturen die nog niet zijn betaald maar die nog niet voorbij de vervaldatum zijn. Deze klant heeft dus nog enige tijd om zijn factuur te betalen.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Alle openstaande verkoopfacturen<\/span><\/h1>\n\r<p class=\"p_Normal\">Toont alle facturen die nog niet betaald zijn.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Alle nog te betalen creditnota\'s<\/span><\/h1>\n\r<p class=\"p_Normal\">Toont alle creditnota\'s die nog betaald moeten worden.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Alle betaalde facturen<\/span><\/h1>\n\r<p class=\"p_Normal\">Toont alle facturen die reeds betaald zijn.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Afhankelijk dus van de gemaakt keuze in dit menu, krijgt u de informatie zoals beschreven. Via printen kunt u vervolgens diverse lijsten gaan printen.<\/p>\n\r"
})
