hmLoadTopic({
hmKeywords:"Printen",
hmTitle:"Printen",
hmDescription:"Via deze keuze kunt u allerlei documenten, lijsten, etiketten enz... gaan printen.",
hmPrevLink:"instellen-snelprinten.html",
hmNextLink:"print-nu-menu.html",
hmParentLink:"de_verschillende_keuzes.html",
hmBreadCrumbs:"Algemeen &gt; <a href=\"de_verschillende_keuzes.html\">De \'Bewerkingen\' knoppenbalk<\/a>",
hmTitlePath:"Algemeen > De \'Bewerkingen\' knoppenbalk > Printen",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Printen<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">Via deze keuze kunt u allerlei documenten, lijsten, etiketten enz... gaan printen.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><span class=\"f_Heading1\">Werkwijze<\/span><\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin-left: 0.8750rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>Door op de knop \'Printen\' te klikken met de muis<\/p>\n\r<div class=\"p_Normal\" style=\"margin: 0 0 0 2.5000rem;\"><img alt=\"clip0535\" style=\"width:80%;max-width:707px;height:auto;border:none\" src=\".\/images\/clip0535.png\"\/><\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin-left: 0.8750rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>Door op de <a href=\"axito-smartkey.html\" class=\"topiclink\">smartkey<\/a> \'P\' van het toetsenbord te drukken (zoals aangegeven bij deze keuze in de rode kleur)<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Het printmenu<\/span><\/h1>\n\r<p class=\"p_Normal\">Nadat u \'Printen\' heeft geselecteerd, verschijnt er altijd een printmenu.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Voorbeelden van het printmenu selecteert vanuit verschillende bestanden<\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.80; padding: 0 0 0 0; margin: 0 0 0 0.8750rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0.3125rem; border:none\"><p class=\"p_Normal\" style=\"text-align: center; margin: 0 0 0 0;\">Klantenbestand<\/p>\n\r<div class=\"p_Normal\" style=\"text-align: center; margin: 0 0 0 0;\"><div style=\"margin:0 auto 0 auto;width:80%;max-width:210px;height:auto;\"><img alt=\"clip0536\" style=\"width:100%;height:auto;border:none\" src=\".\/images\/clip0536.png\"\/><\/div><\/div>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0.3125rem; border:none\"><p class=\"p_Normal\" style=\"text-align: center; margin: 0 0 0 0;\">Facturen\/creditnota\'s<\/p>\n\r<div class=\"p_Normal\" style=\"text-align: center; margin: 0 0 0 0;\"><div style=\"margin:0 auto 0 auto;width:80%;max-width:410px;height:auto;\"><img alt=\"clip0537\" style=\"width:100%;height:auto;border:none\" src=\".\/images\/clip0537.png\"\/><\/div><\/div>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Welke keuzes er in dit printmenu staan, wordt bepaalt door het bestand van waaruit u het \'Printen\' heeft geselecteerd. Vervolgens maakt u een keuze in dit printmenu.<\/p>\n\r"
})
