hmLoadTopic({
hmKeywords:"",
hmTitle:"Relatiebeheer",
hmDescription:"Met relatiebeheer bedoelen we het beheren van uw:  Klanten Uw relaties aan wie u goederen en\/of diensten verkoopt. Leveranciers Uw relaties bij wie u goederen en\/of diensten a",
hmPrevLink:"de_overige_keuzes.html",
hmNextLink:"werknemers.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Relatiebeheer",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Relatiebeheer<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">Met relatiebeheer bedoelen we het beheren van uw:<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.80; padding: 0 0 0 0; margin: 0 0 0 1.5000rem;\"><table class=\"AxitoTableLarge\" >\n\r<tr class=\"AxitoTableLarge\">\n\r<td class=\"AxitoTableLarge\"><p class=\"p_Normal\"><span style=\"font-weight: bold;\"><a href=\"klanten.html\" class=\"topiclink\">Klanten<\/a><\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr class=\"AxitoTableLarge\">\n\r<td class=\"AxitoTableLarge\"><p class=\"p_Normal\" style=\"margin: 0 0 0 2.5000rem;\">Uw relaties aan wie u goederen en\/of diensten verkoopt.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr class=\"AxitoTableLarge\">\n\r<td class=\"AxitoTableLarge\"><p class=\"p_Normal\"><span style=\"font-weight: bold;\"><a href=\"leveranciers.html\" class=\"topiclink\">Leveranciers<\/a><\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr class=\"AxitoTableLarge\">\n\r<td class=\"AxitoTableLarge\"><p class=\"p_Normal\" style=\"margin: 0 0 0 2.5000rem;\">Uw relaties bij wie u goederen en\/of diensten aankoopt<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr class=\"AxitoTableLarge\">\n\r<td class=\"AxitoTableLarge\"><p class=\"p_Normal\"><span style=\"font-weight: bold;\"><a href=\"werknemers.html\" class=\"topiclink\">Werknemers<\/a><\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr class=\"AxitoTableLarge\">\n\r<td class=\"AxitoTableLarge\"><p class=\"p_Normal\" style=\"margin: 0 0 0 2.5000rem;\">Hier kunt u zowel uw werknemers als uw vertegenwoordigers beheren.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr class=\"AxitoTableLarge\">\n\r<td class=\"AxitoTableLarge\"><p class=\"p_Normal\"><span style=\"font-weight: bold;\"><a href=\"prospectie_klanten.html\" class=\"topiclink\">Prospectie klanten<\/a><\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr class=\"AxitoTableLarge\">\n\r<td class=\"AxitoTableLarge\"><p class=\"p_Normal\" style=\"margin: 0 0 0 2.5000rem;\">Mogelijke klanten, die op dit moment nog geen klant zijn, maar waarvan u toch informatie wenst bij te houden, kunt u hier beheren.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr class=\"AxitoTableLarge\">\n\r<td class=\"AxitoTableLarge\"><p class=\"p_Normal\"><span style=\"font-weight: bold;\"><a href=\"adresboek.html\" class=\"topiclink\">Adresboek<\/a><\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr class=\"AxitoTableLarge\">\n\r<td class=\"AxitoTableLarge\"><p class=\"p_Normal\" style=\"margin: 0 0 0 2.5000rem;\">Hierin kunt u alle overige relaties beheren.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r"
})
