hmLoadTopic({
hmKeywords:"",
hmTitle:"Snelprinten",
hmDescription:"De keuze \'Snelprinten\' wordt slecht bij een beperkt aantal bestanden getoond. Momenteel is dat enkel bij de verkoopdocumenten (offertes, bestelbonnen, leveringsbonnen en...",
hmPrevLink:"geavanceerde-filter.html",
hmNextLink:"snelprinten-(uitbreiding).html",
hmParentLink:"de_verschillende_keuzes.html",
hmBreadCrumbs:"Algemeen &gt; <a href=\"de_verschillende_keuzes.html\">De \'Bewerkingen\' knoppenbalk<\/a>",
hmTitlePath:"Algemeen > De \'Bewerkingen\' knoppenbalk > Snelprinten",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Snelprinten<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">De keuze \'Snelprinten\' wordt slecht bij een beperkt aantal bestanden getoond. Momenteel is dat enkel bij de verkoopdocumenten (offertes, bestelbonnen, leveringsbonnen en facturen).<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Werkwijze<\/span><\/h1>\n\r<p class=\"p_Normal\">Om het \'Snelprinten\' uit te leggen, gaan we als voorbeeld een factuur printen.<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin-left: 0.8750rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>Selecteer in &nbsp;het hoofdemnu de keuze \'Facturen\/creditnota\'. De facturen worden getoond.<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin-left: 0.8750rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>Om een factuur te printen<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 2.4375rem; margin-left: 0.8750rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#9642;<\/span>Door op \'Snelprinten\' te klikken met de muis<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 2.4375rem; margin-left: 0.8750rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#9642;<\/span>Door de <a href=\"axito-smartkey.html\" class=\"topiclink\">smartkey<\/a> \'Ctrl + P\' te drukken (zoals aangegeven bij deze keuze in de rode kleur)<\/p>\n\r<div class=\"p_Normal\" style=\"margin: 0 0 0 2.5000rem;\"><img alt=\"clip0445\" style=\"width:80%;max-width:1904px;height:auto;border:none\" src=\".\/images\/clip0445.png\"\/><\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Vervolgens wordt de factuur geprint, waarbij gebruik gemaakt wordt van layout 1. De printer waarnaar dit gestuurd wordt, is de standaard printen zoals deze is ingesteld in Windows.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
