hmLoadTopic({
hmKeywords:"",
hmTitle:"Snelfilter",
hmDescription:"Niet voor elk bestand is er snelfilter beschikbaar. Wanneer u \'Filter\' selecteert, zal  een snelfilter-scherm getoond worden. Maar voor bestanden waarvoor dus geen snelfilter...",
hmPrevLink:"filter.html",
hmNextLink:"geavanceerde-filter.html",
hmParentLink:"filter.html",
hmBreadCrumbs:"Algemeen &gt; <a href=\"de_verschillende_keuzes.html\">De \'Bewerkingen\' knoppenbalk<\/a> &gt; <a href=\"filter.html\">Filter<\/a>",
hmTitlePath:"Algemeen > De \'Bewerkingen\' knoppenbalk > Filter > Snelfilter",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Snelfilter<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">Niet voor elk bestand is er snelfilter beschikbaar. Wanneer u \'<a href=\"filter.html\" class=\"topiclink\">Filter<\/a>\' selecteert, zal &nbsp;een snelfilter-scherm getoond worden. Maar voor bestanden waarvoor dus geen snelfilter is voorzien, wordt &nbsp;de \'<a href=\"geavanceerde-filter.html\" class=\"topiclink\">Geavanceerde filter<\/a>\' getoond.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<div class=\"p_Normal\" style=\"margin: 0 0 0 2.5000rem;\"><img alt=\"clip0362\" style=\"width:80%;max-width:489px;height:auto;border:none\" src=\".\/images\/clip0362.png\"\/><\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">U kunt hierbij meerdere zoektermen invullen, ieder gescheiden door een spatie.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Wanneer u niets invult en direct \'<a href=\"het-toetsenbord.html#enter\" class=\"topiclink\">Enter<\/a>\' drukt, wordt automatisch overgeschakeld naar de \'<a href=\"geavanceerde-filter.html\" class=\"topiclink\">Geavanceerde filter<\/a>\'.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.80; padding: 0 0 0 0; margin: 0 0 0 0.8125rem;\"><table class=\"Voorbeeld\" style=\"width:95%; background-color:#ffffff; border-color:#e0e0e0 #808080 #808080 #e0e0e0; border-style:solid; border-width:0.1875rem; border-spacing:0;\">\n\r<tr class=\"Voorbeeld\">\n\r<td class=\"Voorbeeld\" style=\"border-color:#808080 #e0e0e0 #e0e0e0 #808080; border-style:solid; border-width:thin;\"><div class=\"p_Normal\" style=\"text-align: center;\"><div style=\"margin:0 auto 0 auto;width:40%;max-width:649px;height:auto;\"><img alt=\"clip0409\" style=\"width:100%;height:auto;border:none\" src=\".\/images\/clip0409.png\"\/><\/div><\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.8125rem;\">Stel dat we vanuit het klantenbestand alle klanten zoekt die wonen in Hasselt en een BVBA als vennootschap hebben.<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.8125rem;\">Dan vult u in het Snelfilter-scherm deze 2 zoektermen in gescheiden door een spatie<\/p>\n\r<div class=\"p_Normal\" style=\"margin: 0 0 0 2.4375rem;\"><img alt=\"clip0531\" style=\"width:80%;max-width:490px;height:auto;border:none\" src=\".\/images\/clip0531.png\"\/><\/div>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 2.4375rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Wanneer u vervolgens \'Enter\' drukt, zal de snelfilter geactiveerd worden. Het klantenbestand wordt opnieuw getoond met enkel klanten waar de 2 zoektermen gekend zijn.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r"
})
