hmLoadTopic({
hmKeywords:"Terugname artikelen",
hmTitle:"Terugname artikelen (retour)",
hmDescription:"In de praktijk blijkt dat er regelmatig artikelen worden terug gebracht en omgeruild. We moeten echter opletten dat de voorraad blijft kloppen, zowel voor het artikel dat terug...",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Technische info",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Terugname artikelen (retour)<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">In de praktijk blijkt dat er regelmatig artikelen worden terug gebracht en omgeruild. We moeten echter opletten dat de voorraad blijft kloppen, zowel voor het artikel dat terug genomen wordt als voor het artikel dat in de plaats wordt mee genomen. Het komt er eigenlijk op neer, dat het terug genomen artikel in de kassa wordt toegevoegd, echter het aantal MOET een negatief getal zijn. Dit zal ervoor zorgen dat de voorraad met 1 stuk zal worden opgehoogd.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">De te volgen procedure<\/span><\/h1>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">Om dit op een zo eenvoudig mogelijke manier te kunnen doen, hebben we volgende procedure ontwikkeld :<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Voordat u het terug te nemen artikel scant of toevoegt, moet u eerst op de \'-\' toets drukken. Dit zal door de computer geregistreerd worden.<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Wanneer u nu binnen de 10 seconden een barcode van het artikel scant of op de &lt;T&gt; toets drukt, zal automatisch het veld \'Aantal\' van het nieuwe <a href=\"enkele_termen__bestand_record_.html\" class=\"topiclink\">record<\/a> in de kassaverkoop een waarde -1 hebben.<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Vervolgens gaat u gewoon verder met het inscannen van andere artikelen of met het afrekenen van de verkoop.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
