hmLoadTopic({
hmKeywords:"Traceren artikelen",
hmTitle:"Traceren artikelen",
hmDescription:"Via het traceren van artikelen krijgt u een overzicht van alle aan- en verkoopdocumenten te zien, die met elkaar zijn gelinkt (via een traceringscode). U kunt dit overzicht...",
hmPrevLink:"strikt_voorraadbeheer.html",
hmNextLink:"overzicht_niet-aangepaste_arti.html",
hmParentLink:"voorraadbeheer2.html",
hmBreadCrumbs:"<a href=\"voorraadbeheer2.html\">Voorraad- &amp; aankoopbeheer<\/a>",
hmTitlePath:"Voorraad- & aankoopbeheer > Traceren artikelen",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Traceren artikelen<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Comment\"><span class=\"f_Comment\">Via het traceren van artikelen krijgt u een overzicht van alle aan- en verkoopdocumenten te zien, die met elkaar zijn gelinkt (via een traceringscode). U kunt dit overzicht opvragen voor elk artikel dat voorkomt in de aankoopbestelbonnen en aankoop-leveringsbonnen (en ook voor de offertes, bestelbonnen, leveringsbonnen en facturen):<\/span><\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>Via de keuze &lt;V&gt;ideo document, krijgt u de verschillende videoregels van het document te zien.<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>Vervolgens selecteert u de keuze &lt;H&gt;istorieken, waardoor in een dialoogvenster de verschillende mogelijkheden worden getoond.<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>Selecteer hierin de keuze \'Traceren\/opvolgen artikel\'.<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 1.6250rem; margin: 0 0 0 1.5000rem;\"><span class=\"f_Normal\" style=\"font-family: \'Courier New\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">o<\/span>Waarna u een overzicht krijgt van de verschillende (gelinkte) documenten.<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0;\">De overige beschrijving vindt u terug via volgende link: <a href=\"traceren_artikelen.html\" class=\"topiclink\">Verkoopbeheer-Traceren artikelen.<\/a><\/p>\n\r"
})
