hmLoadTopic({
hmKeywords:"Vervaldagboek",
hmTitle:"Vervaldagboek",
hmDescription:"Hierbij krijgt u een menu te zien met de volgende keuzes:",
hmPrevLink:"rekeningnummers_ivm_bankboekin.html",
hmNextLink:"aanmaningen.html",
hmParentLink:"boekhouding_algemeen.html",
hmBreadCrumbs:"<a href=\"boekhouding_algemeen.html\">Boekhouding<\/a>",
hmTitlePath:"Boekhouding > Vervaldagboek",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Vervaldagboek<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">Hierbij krijgt u een menu te zien met de volgende keuzes:<\/p>\n\r<div class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\"><img alt=\"clip0178\" style=\"width:100%;max-width:427px;height:auto;border:none\" src=\".\/images\/clip0178.jpg\"\/><\/div>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">Deze keuzes worden in de volgende subsecties besproken:<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5625rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Afpunten<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5625rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Openstaande aankoopboekstukken (hierin zijn de opties &lt;1&gt; t.e.m. &lt;4&gt; opgenomen)<\/p>\n\r<p class=\"p_Normal\" style=\"text-indent: 0; padding-left: 0.8125rem; margin: 0 0 0 1.5625rem;\"><span class=\"f_Normal\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span>Openstaande verkoopboekstukken (hierin zijn de opties &lt;5&gt; t.e.m. &lt;8&gt; opgenomen)<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">Meer informatie over <span style=\"font-style: italic;\">&lt;I&gt;nzage periode<\/span> vindt u in de sectie <a href=\"instellen_boekhoudperiode_datu.html\" class=\"topiclink\">Instellen boekhoudperiode<\/a>.<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"margin: 0 0 0 0.7500rem;\">&nbsp;<\/p>\n\r"
})
