hmLoadTopic({
hmKeywords:"Voorraad- & aankoopbeheer",
hmTitle:"Voorraad- & aankoopbeheer",
hmDescription:"Deze module bestaat uit verschillende submodules, die elk een specifieke functie in het het globale voorraadbeheer hebben. Welke zijn deze modules:",
hmPrevLink:"samenstellingen.html",
hmNextLink:"procedures.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Voorraad- & aankoopbeheer",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Voorraad- &amp; aankoopbeheer<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">Deze module bestaat uit verschillende submodules, die elk een specifieke functie in het het globale voorraadbeheer hebben. Welke zijn deze modules:<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\"><a href=\"voorraad.html\" class=\"topiclink\">Voorraad<\/a><\/span><\/h1>\n\r<p class=\"p_Normal\">De voorraad wordt genoteerd per artikel, en kan bijvoorbeeld via het artikelbestand worden opgezocht<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\"><a href=\"inventaris.html\" class=\"topiclink\">Inventaris<\/a><\/span><\/h1>\n\r<p class=\"p_Normal\">Wat is de huidige totale voorraad van alle artikelen.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\"><a href=\"backorders.html\" class=\"topiclink\">Backorders<\/a><\/span><\/h1>\n\r<p class=\"p_Normal\">Wanneer een klant een bestelling plaatst maar de huidige voorraad niet toereikend is, kunt u voor deze klant een backorder opstellen voor het aantal artikelen die nog nageleverd worden.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\"><a href=\"besteladviezen.html\" class=\"topiclink\">Besteladviezen<\/a><\/span><\/h1>\n\r<p class=\"p_Normal\">Via deze module kunt u een lijst bekomen van alle artikelen die u moet bestellen om de voorraad terug op niveau te krijgen.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\"><a href=\"aankoop_bestelbon.html\" class=\"topiclink\">Aankoopbestelbon<\/a><\/span><\/h1>\n\r<p class=\"p_Normal\">Deze module is speciaal ontwikkeld voor het plaatsen van bestellingen bij uw leveranciers. Hierbij kunt u gebruik maken van de module \'Besteladviezen\', waardoor de bestelbon snel en eenvoudig wordt opgesteld.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\"><a href=\"aankoop_leveringsbon.html\" class=\"topiclink\">Aankoopleveringsbon<\/a><\/span><\/h1>\n\r<p class=\"p_Normal\">Via deze module kunt u de binnenkomende artikelen controleren en registreren.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\"><a href=\"initialisatie_voorraad.html\" class=\"topiclink\">Initialisatie voorraad<\/a><\/span><\/h1>\n\r<p class=\"p_Normal\">U kunt op een snelle manier de nieuwe voorraad toestand ingeven (tellen van de voorraad).<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\"><a href=\"voorraad_transfert.html\" class=\"topiclink\">Voorraad transfert<\/a><\/span><\/h1>\n\r<p class=\"p_Normal\">Indien u met de module \'Locaties\' werkt, kunt u op een eenvoudige manier bepaalde artikelen van de ene naar de andere locatie verplaatsen.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
