hmLoadTopic({
hmKeywords:"Werkzaamheden",
hmTitle:"Werkzaamheden",
hmDescription:"Een werkzaamheid kunt u beschouwen als een artikel, maar dan specifiek toegespitst op \'werk\' en \'diensten\'. Voorbeelden hiervan zijn: uurlonen, plaatsingskosten,...",
hmPrevLink:"overige_mogelijkheden.html",
hmNextLink:"samenstellingen.html",
hmParentLink:"artikelenbeheer2.html",
hmBreadCrumbs:"<a href=\"artikelenbeheer2.html\">Artikelenbeheer<\/a>",
hmTitlePath:"Artikelenbeheer > Werkzaamheden",
hmHeader:"<p class=\"p_Titeltekstinbalk\"><span class=\"f_Titeltekstinbalk\">Werkzaamheden<\/span><\/p>\n\r",
hmBody:"<p class=\"p_Normal\">Een werkzaamheid kunt u beschouwen als een artikel, maar dan specifiek toegespitst op \'werk\' en \'diensten\'. Voorbeelden hiervan zijn: uurlonen, plaatsingskosten, transportkosten...<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.80; padding: 0 0 0 0; margin: 0 0 0 0.8750rem;\"><table class=\"Voorbeeld\" >\n\r<tr class=\"Voorbeeld\">\n\r<td class=\"Voorbeeld\"><h3 class=\"p_Heading3\"><span class=\"f_Heading3\">Voorbeeld: <\/span><\/h3>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">Toevoegen werkzaamheid: <\/span>Het toevoegen van een werkzaamheid lijkt sterk op het toevoegen van een artikel. Hierbij worden echter een beperkter aantal gegevens opgevraagd.<\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">Werknummer<\/span>: Het werknummer heeft een lengte van 5 karakters, en wordt niet vooraf gegaan door een artikelgroepnummer.<\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">Omschrijving werkzaamheid<\/span>: Hier vult u een omschrijving van maximaal 60 karakters in.<\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">Aantal<\/span>: Indien u hier het getal 0 invult, zal straks op het moment dat U deze werkzaamheid overbrengt naar een offerte, bon of factuur, het veld \'aantal\' worden opgevraagd. <\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">Eenheid<\/span>: Dit is de verkoopeenheid, vb.: uur. <\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">Verkoopprijs<\/span>: Dit is verkoopprijs exclusief BTW. <\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">Korting %<\/span>: Geeft het verschil weer tussen verkoopprijs en kostprijs. <\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">BTW-code<\/span>: Wanneer u op &lt;F5&gt; drukt, krijgt u een overzicht van de verschillende BTW codes, met hun respectievelijke BTW-percentage. Deze percentages kunt u steeds wijzigen. <\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">Tegenrekening<\/span>: Deze tegenrekening is enkel van toepassing indien u gebruik maakt van AXITO Boekhouding. <\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">Kenmerken<\/span>: Met behulp van &lt;F5&gt; kunt u verschillende kenmerken overbrengen.<\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
